### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by AbbasHejazi** [hkhojasteh/Bag-of-Visual-Words#1]
dear Hadi, 
we are faced a problem in svm 
in this line exactly
 " Ptr<TrainData> td = TrainData::create(inputData, ROW_SAMPLE, inputDataLables);"
I think the error is on " InputData " and " inputDataLables" 
the error is : opencv error : assertion failed (_queryDesritors.type() == trainDescType ) in cv:BFMatcher .....
Thank you in advance
Best Regards, 
Abbas Hejazi

**Comment by AbbasHejazi** [comment]
I think the problem is as I told you, but I treated it .
Because I have another problem in " getHistogramFast() " .

**Comment by hkhojasteh** [comment]
To change the path, check the DATASET_PATH variable. As I wrote, images must be split by the folders in the DATASET_PATH with specific names (DATASET_PATH + className + "\\image_" + ss.str() + IMAGE_EXT)).
