### ISSUE TITLE
xfeatures2d.hpp

### ISSUE THREAD

**Issue by juneraymagusara** [hkhojasteh/Bag-of-Visual-Words#3]
Hey, I would like to ask what version of OpenCV did you use to develop this? And if it's OpenCV 3.x, since sift is already patented, how did you use or acquire the library so that you will be able to use its functions?

**Comment by hkhojasteh** [comment]
@eight-11-1996 Thanks for your interest!
The SIFT and SURF implementations are no longer included in the OpenCV library by default. SIFT and SURF are examples of algorithms that OpenCV calls “non-free” modules. These algorithms are patented by their respective creators, and while they are free to use in academic and research settings, you should technically be obtaining a license/permission from the creators if you are using them in a commercial (i.e. for-profit) application.
With OpenCV 3 came a big push to move many of these “non-free” modules out of the default OpenCV install and into the [opencv_contrib package](https://github.com/opencv/opencv_contrib). The opencv_contrib  packages contains implementations of algorithms that are either patented or in experimental development.
So this algorithm is included in the [opencv contrib repo](https://github.com/opencv/opencv_contrib).

**Comment by juneraymagusara** [comment]
We've tried using the Cmake to compile these opencv_contrib package to be able to use those modules but it didn't work.

**Comment by hkhojasteh** [comment]
I think it's better to ask about this problem in the [opencv_contrib community](https://github.com/opencv/opencv_contrib/issues). They can help you.

**Comment by juneraymagusara** [comment]
Thank you!
